import Head from 'next/head'
import React from 'react'
import Navbar from '@components/Layout/Navbar'
import styles from "./Layout.module.scss"


const Index = ({ children }) => {

    return (
        <>
            <Head>
                <title>Git Hub API</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            <main className={styles.main}>{children}</main>
        </>
    )
}

export default Index